require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');

const SQL_DIR = path.join(__dirname, '..', 'sql');
const MAX_INSERT_CHUNK_BYTES = 1024 * 1024;

function chunkRows(rows, escape) {
  const chunks = [];
  let current = [];
  let currentSize = 0;

  for (const row of rows) {
    const tuple = `(${Object.values(row).map(escape).join(',')})`;
    if (current.length > 0 && currentSize + tuple.length > MAX_INSERT_CHUNK_BYTES) {
      chunks.push(current);
      current = [];
      currentSize = 0;
    }
    current.push(tuple);
    currentSize += tuple.length + 1;
  }

  if (current.length > 0) {
    chunks.push(current);
  }
  return chunks;
}

function formatCreateTable(createTableSql, table, dbName) {
  const cleaned = createTableSql.replace(/ AUTO_INCREMENT=\d+/, '');
  const qualified = `\`${dbName}\`.\`${table}\``;
  const createTable = cleaned.replace(
    /^CREATE TABLE `[^`]+`/,
    `CREATE TABLE IF NOT EXISTS ${qualified}`,
  );
  return `DROP TABLE IF EXISTS ${qualified} ;\n\n${createTable};\n`;
}

function buildSchemaSql(tables, dbName, schemaStatements) {
  const timestamp = new Date().toLocaleString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  const lines = [
    '-- MySQL Script generated by update_db_migration_scripts.js',
    `-- ${timestamp}`,
    '-- Model: about_games_db',
    '-- MySQL Workbench Forward Engineering',
    '',
    'SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;',
    'SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;',
    "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';",
    '',
    '-- -----------------------------------------------------',
    `-- Schema ${dbName}`,
    '-- -----------------------------------------------------',
    `CREATE SCHEMA IF NOT EXISTS \`${dbName}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;`,
    `USE \`${dbName}\` ;`,
    '',
  ];

  for (const table of tables) {
    lines.push(
      '-- -----------------------------------------------------',
      `-- Table \`${dbName}\`.\`${table}\``,
      '-- -----------------------------------------------------',
      schemaStatements[table],
      '',
    );
  }

  lines.push('SET SQL_MODE=@OLD_SQL_MODE;');
  lines.push('SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;');
  lines.push('SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;');

  return lines.join('\n');
}

function buildReferentialActionsSql(tables, dbName, updatedAtColumns) {
  const lines = [
    `USE ${dbName};`,
    '',
    '-- Modify updated_at columns to auto-update timestamps on row update',
  ];

  for (const table of tables) {
    if (updatedAtColumns.includes(table)) {
      lines.push(
        `ALTER TABLE \`${table}\``,
        `    MODIFY COLUMN \`updated_at\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;`,
      );
    }
  }

  return lines.join('\n') + '\n';
}

function buildPopulateSql(tables, dbName, dataByTable, escape) {
  const timestamp = new Date().toISOString().slice(0, 19).replace('T', ' ');

  const lines = [
    '-- MySQL dump generated by update_db_migration_scripts.js',
    '--',
    `-- Host: localhost    Database: ${dbName}`,
    '-- ------------------------------------------------------',
    '',
    '/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;',
    '/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;',
    '/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;',
    '/*!50503 SET NAMES utf8 */;',
    '/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;',
    "/*!40103 SET TIME_ZONE='+00:00' */;",
    '/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;',
    '/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;',
    "/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;",
    '/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;',
    '',
  ];

  for (const table of tables) {
    const rows = dataByTable[table];
    if (!rows || rows.length === 0) {
      continue;
    }

    lines.push(
      '--',
      `-- Dumping data for table \`${table}\``,
      '--',
      '',
      `LOCK TABLES \`${table}\` WRITE;`,
      `/*!40000 ALTER TABLE \`${table}\` DISABLE KEYS */;`,
    );

    for (const chunk of chunkRows(rows, escape)) {
      lines.push(
        `INSERT INTO \`${table}\` VALUES ${chunk.join(',')};`,
      );
    }

    lines.push(`/*!40000 ALTER TABLE \`${table}\` ENABLE KEYS */;`);
    lines.push('UNLOCK TABLES;');
    lines.push('');
  }

  lines.push(
    '/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;',
    '',
    '/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;',
    '/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;',
    '/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;',
    '/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;',
    '/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;',
    '/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;',
    '/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;',
    '',
    `-- Dump completed on ${timestamp}`,
    '',
  );

  return lines.join('\n');
}

async function main() {
  const { DB_USERNAME, DB_PASSWORD, DB_DATABASE_NAME, DB_HOST, DB_PORT } =
    process.env;

  if (!DB_DATABASE_NAME) {
    throw new Error('DB_DATABASE_NAME env var is required');
  }

  const connection = await mysql.createConnection({
    host: DB_HOST,
    port: Number(DB_PORT),
    user: DB_USERNAME,
    password: DB_PASSWORD,
    database: DB_DATABASE_NAME,
    dateStrings: true,
  });

  console.info('Connected to MySQL server.');

  const [tablesRows] = await connection.query(
    `SELECT TABLE_NAME
       FROM INFORMATION_SCHEMA.TABLES
      WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE'
      ORDER BY TABLE_NAME`,
    [DB_DATABASE_NAME],
  );
  const tables = tablesRows.map((row) => row.TABLE_NAME);
  console.info(`Found ${tables.length} tables: ${tables.join(', ')}`);

  const escape = (value) => connection.escape(value);
  const schemaStatements = {};
  const dataByTable = {};
  const updatedAtTables = [];

  for (const table of tables) {
    const [createRows] = await connection.query(
      `SHOW CREATE TABLE \`${table}\``,
    );
    schemaStatements[table] = formatCreateTable(
      createRows[0]['Create Table'],
      table,
      DB_DATABASE_NAME,
    );

    const [rows] = await connection.query(`SELECT * FROM \`${table}\``);
    if (rows.length > 0) {
      dataByTable[table] = rows;
      console.info(`Fetched ${rows.length} rows from \`${table}\`.`);
    } else {
      console.info(`Table \`${table}\` is empty, no data exported.`);
    }

    const [cols] = await connection.query(
      `SELECT COLUMN_NAME
         FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = 'updated_at'`,
      [DB_DATABASE_NAME, table],
    );
    if (cols.length > 0) {
      updatedAtTables.push(table);
    }
  }

  const schemaSql = buildSchemaSql(tables, DB_DATABASE_NAME, schemaStatements);
  const referentialSql = buildReferentialActionsSql(
    tables,
    DB_DATABASE_NAME,
    updatedAtTables,
  );
  const populateSql = buildPopulateSql(
    tables,
    DB_DATABASE_NAME,
    dataByTable,
    escape,
  );

  fs.writeFileSync(path.join(SQL_DIR, 'db_schema.sql'), schemaSql, 'utf8');
  fs.writeFileSync(
    path.join(SQL_DIR, 'db_referential_actions.sql'),
    referentialSql,
    'utf8',
  );
  fs.writeFileSync(path.join(SQL_DIR, 'db_populate.sql'), populateSql, 'utf8');

  console.info('db_schema.sql updated.');
  console.info('db_referential_actions.sql updated.');
  console.info('db_populate.sql updated.');

  await connection.end();
}

main().catch((err) => {
  console.error('Error during DB migration scripts generation:', err);
  process.exit(1);
});
