SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `about_games_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `about_games_db` ;

-- Drop tables if they exist
DROP TABLE IF EXISTS `videos_has_games`;
DROP TABLE IF EXISTS `videos`;
DROP TABLE IF EXISTS `yt_channel`;
DROP TABLE IF EXISTS `games_has_companies`;
DROP TABLE IF EXISTS `companies`;
DROP TABLE IF EXISTS `games`;
DROP TABLE IF EXISTS `users`;

-- MySQL Script generated by MySQL Workbench
-- Fri Jun 13 13:00:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema about_games_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema about_games_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS about_games_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE about_games_db ;

-- -----------------------------------------------------
-- Table about_games_db.games
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS about_games_db.games (
                                                    id INT NOT NULL AUTO_INCREMENT,
                                                    igdb_id INT NOT NULL,
                                                    title TEXT NOT NULL,
                                                    release_date DATE NOT NULL,
                                                    cover_img TEXT NULL,
                                                    boxart_img TEXT NOT NULL,
                                                    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    PRIMARY KEY (id),
    UNIQUE INDEX igdb_id_UNIQUE (igdb_id ASC) VISIBLE,
    FULLTEXT INDEX ft_title (title) INVISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table about_games_db.companies
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS about_games_db.companies (
                                                        id INT NOT NULL AUTO_INCREMENT,
                                                        igdb_id INT NOT NULL,
                                                        name TEXT NOT NULL,
                                                        created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                        updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                        PRIMARY KEY (id),
    UNIQUE INDEX igdb_id_UNIQUE (igdb_id ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table about_games_db.games_has_companies
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS about_games_db.games_has_companies (
                                                                  games_id INT NOT NULL,
                                                                  companies_id INT NOT NULL,
                                                                  PRIMARY KEY (games_id, companies_id),
    INDEX fk_games_has_companies_companies1_idx (companies_id ASC) VISIBLE,
    INDEX fk_games_has_companies_games1_idx (games_id ASC) VISIBLE,
    CONSTRAINT fk_games_has_companies_games1
    FOREIGN KEY (games_id)
    REFERENCES about_games_db.games (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT fk_games_has_companies_companies1
    FOREIGN KEY (companies_id)
    REFERENCES about_games_db.companies (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table about_games_db.yt_channel
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS about_games_db.yt_channel (
                                                         id INT NOT NULL AUTO_INCREMENT,
                                                         name VARCHAR(255) NOT NULL,
    youtube_id VARCHAR(255) NOT NULL,
    description TEXT NULL,
    thumbnail TEXT NULL,
    language VARCHAR(45) NOT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE INDEX name_UNIQUE (name ASC) VISIBLE,
    UNIQUE INDEX youtube_id_UNIQUE (youtube_id ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table about_games_db.videos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS about_games_db.videos (
                                                     id INT NOT NULL AUTO_INCREMENT,
                                                     yt_channel_id INT NOT NULL,
                                                     title TEXT NOT NULL,
                                                     description TEXT NOT NULL,
                                                     release_date DATE NULL,
                                                     created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                     updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                     PRIMARY KEY (id, yt_channel_id),
    INDEX fk_videos_yt_channel1_idx (yt_channel_id ASC) VISIBLE,
    CONSTRAINT fk_videos_yt_channel1
    FOREIGN KEY (yt_channel_id)
    REFERENCES about_games_db.yt_channel (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table about_games_db.videos_has_games
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS about_games_db.videos_has_games (
                                                               videos_id INT NOT NULL,
                                                               videos_yt_channel_id INT NOT NULL,
                                                               games_id INT NOT NULL,
                                                               PRIMARY KEY (videos_id, videos_yt_channel_id, games_id),
    INDEX fk_videos_has_games_games1_idx (games_id ASC) VISIBLE,
    INDEX fk_videos_has_games_videos1_idx (videos_id ASC, videos_yt_channel_id ASC) VISIBLE,
    CONSTRAINT fk_videos_has_games_videos1
    FOREIGN KEY (videos_id , videos_yt_channel_id)
    REFERENCES about_games_db.videos (id , yt_channel_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT fk_videos_has_games_games1
    FOREIGN KEY (games_id)
    REFERENCES about_games_db.games (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table about_games_db.users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS about_games_db.users (
                                                    id INT NOT NULL AUTO_INCREMENT,
                                                    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    admin TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;