-- MySQL Script generated by MySQL Workbench
-- Tue Jun 17 16:46:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema about_games_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema about_games_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `about_games_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `about_games_db` ;

-- -----------------------------------------------------
-- Table `about_games_db`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`games` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`games` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `igdb_id` INT NOT NULL,
                                                        `title` TEXT NOT NULL,
                                                        `release_date` DATE NULL,
                                                        `companies` TEXT NULL,
                                                        `cover_img` TEXT NULL,
                                                        `boxart_img` TEXT NULL,
                                                        `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                        `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                        `ignore_during_search` TINYINT NOT NULL DEFAULT 0,
                                                        PRIMARY KEY (`id`),
    UNIQUE INDEX `igdb_id_UNIQUE` (`igdb_id` ASC) VISIBLE,
    FULLTEXT INDEX `ft_title` (`title`) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `about_games_db`.`yt_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`yt_channel` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`yt_channel` (
                                                             `id` INT NOT NULL AUTO_INCREMENT,
                                                             `name` VARCHAR(255) NOT NULL,
    `youtube_handle` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `thumbnail` TEXT NULL,
    `language` VARCHAR(45) NOT NULL,
    `parsing_attribute` VARCHAR(255) NULL,
    `ignore_episodes_containing` TEXT NULL,
    `ignore_episodes_missing` TEXT NULL,
    `ignore_search_in` TEXT NULL,
    `end_parsing_after` TEXT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `youtube_id` VARCHAR(255) NOT NULL,
    `youtube_uploads_id` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
    UNIQUE INDEX `youtube_id_UNIQUE` (`youtube_handle` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `about_games_db`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`videos` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`videos` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `yt_channel_id` INT NOT NULL,
                                                         `title` TEXT NOT NULL,
                                                         `description` TEXT NOT NULL,
                                                         `release_date` DATE NULL,
                                                         `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                         `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                         `validated` TINYINT NOT NULL DEFAULT 0,
                                                         `games_found_count` INT NOT NULL DEFAULT 0,
                                                         `games_count` INT NOT NULL DEFAULT 0,
                                                         `youtube_id` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_videos_yt_channel1_idx` (`yt_channel_id` ASC) VISIBLE,
    UNIQUE INDEX `youtube_id_UNIQUE` (`youtube_id` ASC) VISIBLE,
    CONSTRAINT `fk_videos_yt_channel1`
    FOREIGN KEY (`yt_channel_id`)
    REFERENCES `about_games_db`.`yt_channel` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `about_games_db`.`videos_has_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`videos_has_games` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`videos_has_games` (
                                                                   `video_id` INT NOT NULL,
                                                                   `game_id` INT NOT NULL,
                                                                   PRIMARY KEY (`video_id`, `game_id`),
    INDEX `fk_videos_has_games_games1_idx` (`game_id` ASC) VISIBLE,
    INDEX `fk_videos_has_games_videos1_idx` (`video_id` ASC) VISIBLE,
    CONSTRAINT `fk_videos_has_games_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `about_games_db`.`videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_videos_has_games_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `about_games_db`.`games` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `about_games_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`users` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`users` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `username` VARCHAR(50) NOT NULL,
    `password_hash` VARCHAR(255) NOT NULL,
    `admin` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
