-- MySQL Script generated by update_db_migration_scripts.js
-- Mon, Aug 31, 2026, 07:24:36 PM
-- Model: about_games_db
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema about_games_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `about_games_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `about_games_db` ;

-- -----------------------------------------------------
-- Table `about_games_db`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`games` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`games` (
  `id` int NOT NULL AUTO_INCREMENT,
  `igdb_id` int NOT NULL,
  `title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `release_date` datetime DEFAULT NULL,
  `companies` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `cover_img` text COLLATE utf8mb4_unicode_ci,
  `boxart_img` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `igdb_id_UNIQUE` (`igdb_id`),
  FULLTEXT KEY `ft_title` (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `about_games_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`users` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `admin` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `about_games_db`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`videos` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`videos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `yt_channel_id` int NOT NULL,
  `title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `release_date` datetime DEFAULT NULL,
  `thumbnail_url` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `validated` tinyint(1) DEFAULT NULL,
  `ignored` tinyint(1) NOT NULL DEFAULT '0',
  `games_found_count` int DEFAULT NULL,
  `games_count` int DEFAULT NULL,
  `has_searched_games` tinyint(1) NOT NULL DEFAULT '0',
  `youtube_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `youtube_id_UNIQUE` (`youtube_id`),
  KEY `fk_videos_yt_channel1_idx` (`yt_channel_id`),
  CONSTRAINT `videos_ibfk_1` FOREIGN KEY (`yt_channel_id`) REFERENCES `yt_channel` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `about_games_db`.`videos_has_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`videos_has_games` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`videos_has_games` (
  `video_id` int NOT NULL,
  `game_id` int NOT NULL,
  `created_at` datetime NOT NULL,
  `rank` int DEFAULT '0',
  PRIMARY KEY (`video_id`,`game_id`),
  KEY `fk_videos_has_games_games1_idx` (`game_id`),
  KEY `fk_videos_has_games_videos1_idx` (`video_id`),
  KEY `fk_videos_has_games_rank_idx` (`rank`),
  CONSTRAINT `fk_videos_has_games_games1` FOREIGN KEY (`game_id`) REFERENCES `games` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_videos_has_games_videos1` FOREIGN KEY (`video_id`) REFERENCES `videos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `about_games_db`.`yt_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `about_games_db`.`yt_channel` ;

CREATE TABLE IF NOT EXISTS `about_games_db`.`yt_channel` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `youtube_handle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `thumbnail_url` text COLLATE utf8mb4_unicode_ci,
  `language` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ignore_episodes_containing` text COLLATE utf8mb4_unicode_ci,
  `ignore_episodes_missing` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `youtube_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `youtube_uploads_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `game_candidate_ai_prompt` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  UNIQUE KEY `youtube_id_UNIQUE` (`youtube_handle`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;